name: compdfkit_flutter
description: ComPDFKit for Flutter is a comprehensive SDK that allows you to quickly add PDF functionality to Android and iOS Flutter applications.
version: 2.3.0
homepage: https://www.compdf.com
repository: https://github.com/ComPDFKit/compdfkit-pdf-sdk-flutter
issue_tracker: https://www.compdf.com/support
documentation: https://www.compdf.com/guides/pdf-sdk/flutter/overview

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:

  plugin:
    platforms:
      android:
        package: com.compdfkit.flutter.compdfkit_flutter
        pluginClass: CompdfkitFlutterPlugin
      ios:
        pluginClass: CompdfkitFlutterPlugin
