name: compdfkit_flutter
description: ComPDFKit for Flutter is a comprehensive SDK that allows you to quickly add PDF functionality to Android and iOS Flutter applications.
version: 2.6.9
homepage: https://www.compdf.com?utm_source=pubdev&utm_medium=dev&utm_campaign=compdf_flutter&ref_platform_id=pubdev_compdfkit
repository: https://github.com/ComPDFKit/compdfkit-pdf-sdk-flutter
issue_tracker: https://www.compdf.com?utm_source=pubdev&utm_medium=dev&utm_campaign=compdf_flutter&ref_platform_id=pubdev_compdfkit
documentation: https://www.compdf.com/guides/pdf-sdk/flutter/overview?utm_source=pubdev&utm_medium=dev&utm_campaign=compdf_flutter&ref_platform_id=pubdev_compdfkit

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:

  plugin:
    platforms:
      android:
        package: com.compdfkit.flutter.compdfkit_flutter
        pluginClass: CompdfkitFlutterPlugin
      ios:
        pluginClass: CompdfkitFlutterPlugin
